pipeline {
   environment {
    //PROJECT = "REPLACE_WITH_YOUR_PROJECT_ID"
	PROJECT = "second-drake-379803"
    APP_NAME = "binary-calculator2"
	//CLUSTER = "REPLACE_WITH_YOUR_CLUSTER_NAME"
    CLUSTER = "sofe3980u"
    CLUSTER_ZONE = "northamerica-northeast1-b"
    IMAGE_TAG = "gcr.io/${PROJECT}/${APP_NAME}"
    JENKINS_CRED = "second-drake-379803"
  }
  
agent {
    kubernetes {   
      label 'sample-app'
      defaultContainer 'jnlp'
    }

}
  tools {
    maven 'maven' 
  }
  stages {
    stage ('Init') {
      steps {
        sh 'echo "Start of Job"'
        sh 'ls -la'
      }
    }
    stage ('test') {
      steps {
        sh 'mvn clean test -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
    stage ('build') {
      steps {
        sh 'mvn package -DskipTests -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
    stage ('Deploy') {
      steps {
        container('kubectl') {
          withCredentials([googleServiceAccount(credentialsId: JENKINS_CRED, projectId: PROJECT)]) {
            sh """
	      gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
              /builder/kubectl apply -f ./YAML/binarycalculator-deployment.yaml --record
              /builder/kubectl set image deployment/${APP_NAME} ${APP_NAME}=${IMAGE_TAG}:${BUILD_NUMBER} --record
            """
          }
        }
      }
    }
  }
}

