pipeline {
  agent any
  tools {
    maven 'maven' 
  }
  stages {
    stage ('Init') {
      steps {
        sh 'echo "Start of Job"'
        sh 'ls -la'
      }
    }
    stage ('test') {
      steps {
        sh 'mvn clean test -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
    stage ('build') {
      steps {
        sh 'mvn package -DskipTests -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
    stage ('Deploy') {
      steps {
        container('kubectl') {
          withCredentials([googleServiceAccount(credentialsId: ' 118049687092540086940', projectId: 'second-drake-379803')]) {
            sh """
	      gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
              /builder/kubectl apply -f ./YAML/binarycalculator-deployment.yaml --record
              /builder/kubectl set image deployment/${APP_NAME} ${APP_NAME}=${IMAGE_TAG}:${BUILD_NUMBER} --record
            """
          }
        }
      }
    }
  }
}
